Reviewable/Reviewable

docs/repositories.md
[issue #666](https://github.com/Reviewable/Reviewable/issues/666): 
- sister PRs:  https://github.com/Reviewable/reviewable-client/pull/94, https://github.com/Reviewable/reviewable-server/pull/25
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/reviewable/reviewable/723)
=> updated doc for fix to issue #666

docs/index.html
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/reviewable/reviewable/744)
=> Preserve aspect ratio of screenshots

docs/repositories.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/reviewable/reviewable/764)
=> Add review.pullRequest.target.headCommitSha to sample condition input structure.

enterprise/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/reviewable/reviewable/778)
=> Fix URL for Docker Hub in enterprise README

enterprise/analytics.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/reviewable/reviewable/850)
=> Document Updated Review Status event.

enterprise/changelog.md
Update Enterprise change log with commits added indication and fix for escaping pull request title Markdown.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/reviewable/reviewable/876)
=> Update Enterprise change log

docs/files.md, docs/repositories.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/reviewable/reviewable/946)
=> Add docs for vendored output property.

docs/discussions.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/reviewable/reviewable/954)
=> Add tip about turning off inferring dispositions.

docs/discussions.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/reviewable/reviewable/959)
=> Tweak disposition keyword docs in light of recent changes.

docs/discussions.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/reviewable/reviewable/960)
=> Default new author-created discussions to Discussing disposition.

docs/repositories.md, enterprise/changelog.md, examples/conditions/ignore_base_changes.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/reviewable/reviewable/965)
=> Document baseChangesOnly and add a sample condition.

docs/reviews.md
And move the anchor up so the link shows the options and they're not blocked by the header
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1002)
=> Fix typos in reviews.md

enterprise/changelog.md, enterprise/config.md
This PR adds documentation for [disabled connections](https://github.com/Reviewable/reviewable-server/issues/244), and adds it to changelog.md.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1006)
=> Update documentation and changelog.md for disabled connections

docs/repositories.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1016)
=> Update completion condition docs for NodeJS 18.x

docs/discussions.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1023)
=> Document all the disposition-setting words

docs/repositories.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1029)
=> Add docs for new webhook payload data

docs/repositories.md
For https://github.com/Reviewable/Reviewable/issues/1035
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1036)
=> Document the tooltip feature for prototype repos

docs/repositories.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1040)
=> Add docs for webhook's review.status field

enterprise/README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1078)
=> Document GHE username's purpose

docs/tips.md, docs/tweaks.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1084)
=> Split CSS out of tips.md into a CSS file

examples/analytics/typescript-postgres-grafana/README.md, examples/analytics/typescript-postgres-grafana/docker-compose.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1086)
=> Update the analytics bridge README

docs/tips.md, docs/tweaks.css
This is for the UI experiments framework, which parses CSS variables and comments to have explanations for colors to be modified.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1087)
=> Add explanations to CSS colors

examples/conditions/ignore_base_changes.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1090)
=> Fix the sample code for ignoring base changes in the completion condition.

enterprise/config.md
Counterpart to https://github.com/Reviewable/reviewable-server/pull/357.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1083)
=> Add docs for new `REVIEWABLE_HOST_INACCESSIBLE` flag.

enterprise/config.md
Docs for https://github.com/Reviewable/reviewable-client/pull/882.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1115)
=> Document `REVIEWABLE_CHAT_URL` env var.

enterprise/api.md, enterprise/config.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1132)
=> Add documentation for REST API

docs/SUMMARY.md, docs/subscriptions.md
Hey @snoack, could you please review my edits, and update the rest of the Subscriptions section to reflect the recent changes?  Thanks.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1148)
=> Update docs for new subscriptions design and add docs on licenses.

enterprise/config.md
Docs counterpart to https://github.com/Reviewable/reviewable-client/pull/1060.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1151)
=> Add docs for `REVIEWABLE_GITHUB_STATUS_URL`.

docs/repositories.md
Docs for https://github.com/Reviewable/reviewable-server/pull/543.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1153)
=> Docs for `coauthors` and `requestedTeams`.

docs/repositories.md, examples/conditions/default.js, examples/conditions/pending_reviewers.js, examples/conditions/pull_approve.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1154)
=> Add example of a Pull Approve-like workflow completion condition.

enterprise/config.md
Docs for https://github.com/Reviewable/reviewable-server/pull/551.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1156)
=> Docs for `REVIEWABLE_REFS_DELETION_DELAY`.

examples/conditions/pull_approve.js
The `reviewed` condition would request teams whenever all selected files weren't reviewed yet.  This was intended to stop requesting teams once sufficient reviewers from those teams were engaged but wasn't working as desired, since any participants with unresolved discussions weren't treated as engaged!
Instead, check if we have enough reviewers overall (even if not yet on the selected files) to reach the target score, and request/unrequest teams accordingly.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1161)
=> Fix `pull_approve` condition example to not request unnecessary teams.

docs/repositories.md, examples/settings/settings.yaml
Added my first pass at integrating the `.reviewable` settings docs into `repositories.md`. Also added an example `settings.yaml` file for review.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1169)
=> Reviewable settings directory docs and example file.

docs/repositories.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1177)
=> Document requirement of repositories being connected for setting files

docs/repositories.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1179)
=> Explicitly document that setting files are only read from the default branch

docs/repositories.md, examples/settings/settings.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1178)
=> Document badgeCondition=requested

docs/repositories.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1181)
=> Document "final" settings option

docs/subscriptions.md, enterprise/api.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1172)
=> Add documentation for /team_constraints API

enterprise/config.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1203)
=> Add documentation for `REVIEWABLE_DISPOSITION_DEFAULTS`.

docs/repositories.md, examples/settings/settings.yaml
Viz https://github.com/Reviewable/reviewable-server/pull/665
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1207)
=> Document `github-status.creator` setting.

docs/repositories.md, examples/settings/settings.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1206)
=> Document badge.commenter file setting

examples/conditions/pending_reviewers.js
To match the new default in https://github.com/Reviewable/reviewable-server/pull/710.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1225)
=> Update pending reviewers default to treat mentionees as pending.

CHANGELOG.md, docs/repositories.md, docs/reviews.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1230)
=> Document publish on push

docs/reviews.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1232)
=> Update documentation for publish on push being restricted to open pull requests

CHANGELOG.md, docs/repositories.md, examples/settings/settings.yaml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1236)
=> Document coverage headers in file-based settings

docs/tips.md, docs/tweaks.css
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1247)
=> Document watermark styling tweaks.

docs/abnormal.md, docs/index.md, enterprise/analytics.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1262)
=> Remove all references to Twitter, mention changelog instead.

docs/reviews.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1260)
=> Update documentation to reflect upcoming changes to publish on push criteria

docs/reviews.md
Add self-closing tags to all icons
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/Reviewable/Reviewable/1264)
=> fix icons with closing tags
